[phases.setup]
# Lista de paquetes 'Nix' que Playwright necesita para Chromium
nixPkgs = [
  "chromium",
  "alsa-lib",
  "at-spi2-atk",
  "atk",
  "cairo",
  "cups",
  "dbus",
  "expat",
  "fontconfig-config",
  "fontconfig",
  "freetype",
  "gdk-pixbuf",
  "glib",
  "gtk3",
  "libGL",
  "libX11",
  "libXScrnSaver",
  "libXcomposite",
  "libXcursor",
  "libXdamage",
  "libXext",
  "libXfixes",
  "libXi",
  "libXrandr",
  "libXrender",
  "libXtst",
  "libgcc",
  "libuuid",
  "nss",
  "pango"
]

[build]
# Le dice a Railway c√≥mo construir e iniciar tu app
installCommand = "npm install"
startCommand = "npm start"